In [1]:
# 1
import numpy as np
x = np.arange(50,100)
x

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [2]:
# 2
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
# 2
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 2
np.zeros(10)+6

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [5]:
# 3
x = np.arange(20,32)
y = np.reshape(x, (3,4), 'C')
print(y)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [6]:
# 4
a = [1,1,1]
arr = np.diag(a)
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [7]:
# 5
x = np.arange(1,6)
D = np.diag(x)
D

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [8]:
# 6
import numpy as np
b = np.array([[5,6,1,10],[21,15,13,7],[6,6,8,9]])
print(sum(sum(b)))
print(b.sum(axis=0))
print(b.sum(axis=1))

107
[32 27 22 26]
[22 56 29]


In [9]:
# 7 
import numpy as np

#Seasons
Seasons = ["2012","2013","2014","2015","2016","2017","2018","2019","2020","2021"]
Sdict = {"2012":0,"2013":1,"2014":2,"2015":3,"2016":4,"2017":5,"2018":6,"2019":7,"2020":8,"2021":9}

#Players
Players = ["KobeBryant","JoeJohnson","LeBronJames","CarmeloAnthony","DwightHoward","ChrisBosh","ChrisPaul","KevinDurant","DerrickRose","DwyaneWade"]
Pdict = {"KobeBryant":0,"JoeJohnson":1,"LeBronJames":2,"CarmeloAnthony":3,"DwightHoward":4,"ChrisBosh":5,"ChrisPaul":6,"KevinDurant":7,"DerrickRose":8,"DwyaneWade":9}

#Salaries
KobeBryant_Salary = [30453805,30453805,23500000,25000000,0,0,0,0,0,0]
JoeJohnson_Salary = [19752645,21466718,23180790,261894,11000000,473835,0,1620564,1620564,0]
LeBronJames_Salary = [17545000,19067500,20644400,22970500,30963450,33285709,35654150,37436858,39219566,41180544]
CarmeloAnthony_Salary = [19444503,21388953,22458401,22875000,24559380,26243760,1512601,1364204,1620564,1669178]
DwightHoward_Salary = [19536360,20513178,21436271,22359364,23180275,23819725,5337000,1620564,1620564,1669178]
ChrisBosh_Salary = [19067500,19067500,20644400,22192730,23741060,0,0,0,0,0]
ChrisPaul_Salary = [18668431,18668431,20068563,21468695,22868827,24599495,35654150,38506482,41358814,30000000]
KevinDurant_Salary = [17832626,17832627,18995624,20158622,26540100,0,30000000,38199000,40108950,42018900]
DerrickRose_Salary = [17632688,17632688,18862876,20093064,21323252,290951,1512601,7317073,7682927,13445120]
DwyaneWade_Salary = [18673000,18673000,15000000,20000000,23200000,0,1512601,1512601,1512601,0]
#Matrix
Salary = np.array([KobeBryant_Salary, JoeJohnson_Salary, LeBronJames_Salary, CarmeloAnthony_Salary, DwightHoward_Salary, ChrisBosh_Salary, ChrisPaul_Salary, KevinDurant_Salary, DerrickRose_Salary, DwyaneWade_Salary])

#Games 
KobeBryant_G = [78,6,35,66,0,0,0,0,0,0]
JoeJohnson_G = [72,79,80,81,78,55,0,0,0,1]
LeBronJames_G = [76,77,69,76,74,82,55,67,45,48]
CarmeloAnthony_G = [67,77,40,72,74,78,10,58,69,58]
DwightHoward_G = [76,71,41,71,74,81,9,69,69,47]
ChrisBosh_G = [74,79,44,53,0,0,0,0,0,0]
ChrisPaul_G = [70,62,82,74,61,58,58,70,70,58]
KevinDurant_G = [81,81,27,72,62,68,78,0,35,40]
DerrickRose_G = [0,10,51,66,64,25,51,50,50,26]
DwyaneWade_G = [69,54,62,74,60,67,72,0,0,0]
#Matrix
Games = np.array([KobeBryant_G, JoeJohnson_G, LeBronJames_G, CarmeloAnthony_G, DwightHoward_G, ChrisBosh_G, ChrisPaul_G, KevinDurant_G, DerrickRose_G, DwyaneWade_G])


#Field Goals
KobeBryant_FG = [738,31,266,398,0,0,0,0,0,0]
JoeJohnson_FG = [445,462,446,377,273,146,0,0,0,1]
LeBronJames_FG = [765,767,624,737,736,857,558,643,422,536]
CarmeloAnthony_FG = [669,743,358,567,602,472,49,336,327,270]
DwightHoward_FG = [470,473,251,372,388,506,43,202,178,91]
ChrisBosh_FG = [485,492,343,358,0,0,0,0,0,0]
ChrisPaul_FG = [412,406,568,515,374,367,302,434,439,325]
KevinDurant_FG = [731,849,238,698,551,630,721,0,324,417]
DerrickRose_FG = [0,58,338,447,460,81,363,369,287,122]
DwyaneWade_FG = [569,415,509,540,414,299,416,0,0,0]
#Matrix
FieldGoals  = np.array([KobeBryant_FG, JoeJohnson_FG, LeBronJames_FG, CarmeloAnthony_FG, DwightHoward_FG, ChrisBosh_FG, ChrisPaul_FG, KevinDurant_FG, DerrickRose_FG, DwyaneWade_FG])
    


In [10]:
# 7 Salary mor baganiin niilber
print("Salary Baganiin niilber = ", Salary.sum(axis=0))
print("Salary Moriin niilber = ", Salary.sum(axis=1))

Salary Baganiin niilber =  [198606558 204764400 204791325 197379869 207376344 108713475 111183103
 127577346 134744550 129982920]
Salary Moriin niilber =  [109407610  79377010 297967677 143136544 141092479 104713190 271861888
 251686449 125793240 100083803]


In [11]:
# 7 Games mor baganiin niilber
print("Games Baganiin niilber = ", Games.sum(axis=0))
print("Games Moriin niilber = ", Games.sum(axis=1))

Games Baganiin niilber =  [663 596 531 705 547 514 333 314 338 278]
Games Moriin niilber =  [185 446 669 603 608 250 663 544 393 458]


In [12]:
# 7 FieldGoals mor baganiin niilber
print("FieldGoals Baganiin niilber = ", FieldGoals.sum(axis=0))
print("FieldGoals Moriin niilber = ", FieldGoals.sum(axis=1))

FieldGoals Baganiin niilber =  [5284 4696 3941 5009 3798 3358 2452 1984 1977 1762]
FieldGoals Moriin niilber =  [1433 2150 6645 4393 2974 1678 4142 5159 2525 3162]
